[project]
name = "donut-camera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fotis Kapotos", email = "fotiskapotos@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
donut-camera = "donut_camera:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
